### ISSUE TITLE
grammar conflicts

### ISSUE THREAD

**Issue by mainiak** [cwdoh/cssparser.js#2]
Hi.

When I use command 'node_modules/.bin/jison src/cssparser.y src/css.l -t -o p.js 2>err.log | tee debug.log', jison gives me 634 conflicts in grammar.

It's possible to make this zero?

update1: note - http://stackoverflow.com/questions/15825195/debugging-in-jison

**Comment by cwdoh** [comment]
I rewrote css parser for improve features, and this issue is cleared at new version.
