### ISSUE TITLE
whitespace in selectors is removed

### ISSUE THREAD

**Issue by tomgenoni** [cwdoh/cssparser.js#6]
If I parse the string:

     .foo .bar { bar:foo; }

The data object contains:

     selector: ".foo.bar"

when it should be:

      selector: ".foo .bar"

**Comment by cwdoh** [comment]
Really too late fix of issue. Thanks again for filing issue, @tomgenoni. :)

**Comment by pnaveen10** [comment]
Still the spacing issue is not fixed for element and class combination selectors:
`div .header { bar:foo; }`
The data object contains:
`selector: "div.header"`
when it should be:
`selector: "div .header"`

**Comment by cwdoh** [comment]
Fixed since version 0.9.0
