### ISSUE TITLE
Parsing type option is ignored

### ISSUE THREAD

**Issue by maxnordlund** [cwdoh/cssparser.js#7]
As far as I can tell, the [type option](../blob/master/lib/cli.js#L51-L55) is totally ignored. The examples in the README indicate that it has not been implemented, but I think the `deep`/`atomic` options would be very useful. This issue is to track any progress of those features, or if they are implemented, update the examples in the README.

I also hope the demo would be updated to allow selecting between the three modes to see how it looks like. Amazing work though, it's very cool to be able to parse CSS in JS. It allows some pretty powerful tools to be built in the language that matters the most for web developers.

**Comment by cwdoh** [comment]
This issue is cleared since rewritten parser. Sorry too late. :)

**Comment by maxnordlund** [comment]
Np, nice to see happening 😸
